apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "impulse.fullname" . }}-config
  labels:
    {{- include "impulse.labels" . | nindent 4 }}
data:
  impulse.yml: |
    {{- $config := deepCopy .Values.impulseConfig -}}
    {{- if $config.messenger -}}
    {{- $_ := unset $config.messenger "template_files" -}}
    {{- end -}}
    {{- if $config.task_management -}}
    {{- $_ := unset $config.task_management "template_files" -}}
    {{- end -}}
    {{- toYaml $config | nindent 4 }}
  {{- range $filename, $spec := include "impulse.customTemplates" . | fromYaml }}
  {{ $filename }}: |
    {{- include "impulse.templateContent" (dict "root" $ "spec" $spec) | nindent 4 }}
  {{- end }}
